import { useMemo, useState } from "react";
import { ArrowUpRight, Bell, CalendarDays, Search, SlidersHorizontal } from "lucide-react";
import { Link } from "wouter";
import AppShell, { PageHeading } from "@/components/AppShell";
import { AnnouncementCard, EmptyState } from "@/components/PortalComponents";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAnnouncements } from "@/hooks/useAnnouncements";

const filters = ["All updates", "Campus life", "Student services", "Opportunities", "Clubs", "Wellbeing", "Sport"];
export default function Announcements() {
  const { data: announcements = [], isLoading } = useAnnouncements();
  const [filter, setFilter] = useState("All updates");
  const [search, setSearch] = useState("");
  const filtered = useMemo(() => announcements.filter(item => (filter === "All updates" || item.category === filter) && `${item.title} ${item.summary}`.toLowerCase().includes(search.toLowerCase())), [announcements, filter, search]);
  return <AppShell><div className="mx-auto max-w-7xl px-5 py-12 sm:px-8 sm:py-16 lg:px-10"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><PageHeading eyebrow="Campus noticeboard" title="Keep up with what’s happening." description="The latest news, opportunities, and small-but-important updates from around campus. Curated for students, refreshed often." /><div className="w-full max-w-sm"><label htmlFor="announcement-search" className="sr-only">Search announcements</label><div className="relative"><Search className="pointer-events-none absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input id="announcement-search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search the noticeboard" className="h-12 rounded-full border-border bg-card pl-11 pr-4 shadow-[0_8px_25px_rgba(36,66,53,0.04)] focus-visible:ring-primary/10" /></div></div></div><div className="mt-10 flex gap-2 overflow-x-auto pb-2 [scrollbar-width:none]"><SlidersHorizontal className="mr-1 mt-2 size-4 shrink-0 text-muted-foreground" />{filters.map(item => <Button key={item} variant="ghost" onClick={() => setFilter(item)} className={`shrink-0 rounded-full px-4 text-xs font-bold ${filter === item ? "bg-primary text-primary-foreground hover:bg-[#0a5d4d] hover:text-primary-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}>{item}</Button>)}</div>{isLoading ? <div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><div className="h-64 animate-pulse rounded-2xl bg-muted" /><div className="h-64 animate-pulse rounded-2xl bg-muted" /><div className="h-64 animate-pulse rounded-2xl bg-muted" /></div> : filtered.length > 0 ? <div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{filtered.map((item, index) => <div key={item.id} className={index === 0 && filter === "All updates" && !search ? "md:col-span-2" : ""}><AnnouncementCard item={item} /></div>)}</div> : <div className="mt-10"><EmptyState icon={<Bell className="size-5" />} title="No announcements found" description="Try a different keyword or filter. New updates will appear here as soon as they are published." /></div>}<div className="mt-12 flex flex-col justify-between gap-5 rounded-2xl border border-border bg-[#eef4ed] p-6 sm:flex-row sm:items-center sm:p-7"><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl bg-white text-primary"><CalendarDays className="size-5" /></div><div><h2 className="text-sm font-extrabold">Looking for something to do?</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Your dashboard has a quick view of upcoming activities and events.</p></div></div><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-extrabold text-primary hover:underline">Go to dashboard <ArrowUpRight className="size-4" /></Link></div></div></AppShell>;
}
