import { useEffect, useState } from "react";
import { Check, Circle, Loader2, Plus, Trash2 } from "lucide-react";
import { api, type Task, type TaskStatus } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

const statusLabel: Record<TaskStatus, string> = { todo: "To do", "in-progress": "In progress", completed: "Completed" };
export default function TaskBoard() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [title, setTitle] = useState("");
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  async function load() { try { setLoading(true); const result = await api.tasks.list(); setTasks(result.data); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load tasks."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function create(event: React.FormEvent) { event.preventDefault(); if (!title.trim()) return; try { const result = await api.tasks.create({ title, assignedUser: "Alex Morgan" }); setTasks(prev => [result.data, ...prev]); setTitle(""); setMessage(result.message || "Task created successfully."); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create task."); } }
  async function cycle(task: Task) { const next: TaskStatus = task.status === "todo" ? "in-progress" : task.status === "in-progress" ? "completed" : "todo"; try { const result = await api.tasks.update(task.id, { status: next }); setTasks(prev => prev.map(item => item.id === task.id ? result.data : item)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update task."); } }
  async function remove(id: string) { try { await api.tasks.remove(id); setTasks(prev => prev.filter(task => task.id !== id)); setMessage("Task deleted successfully."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to delete task."); } }
  return <Card className="border-0 bg-card shadow-[0_12px_35px_rgba(36,66,53,0.06)]"><CardHeader className="flex flex-row items-center justify-between space-y-0 p-7 pb-4"><div><CardTitle className="text-lg font-extrabold tracking-[-0.03em]">My tasks & activities</CardTitle><p className="mt-1 text-xs text-muted-foreground">Live records from the CampusConnect REST API.</p></div><span className="rounded-full bg-secondary px-3 py-1 font-mono text-[10px] uppercase tracking-[0.12em] text-primary">CRUD enabled</span></CardHeader><CardContent className="p-7 pt-2"><form onSubmit={create} className="flex gap-2"><Input value={title} onChange={event => setTitle(event.target.value)} placeholder="Add a new task" className="h-11 rounded-xl bg-background" /><Button type="submit" className="h-11 shrink-0 rounded-xl bg-primary px-4 font-extrabold hover:bg-[#0a5d4d]"><Plus className="mr-1 size-4" />Add</Button></form>{message && <p className="mt-3 text-xs font-semibold text-primary">{message}</p>}{error && <p className="mt-3 text-xs font-semibold text-destructive">{error}</p>}<div className="mt-6 space-y-3">{loading ? <div className="flex items-center gap-2 py-5 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin" />Loading tasks from the API…</div> : tasks.length === 0 ? <p className="py-5 text-sm text-muted-foreground">No tasks yet. Add one above.</p> : tasks.map(task => <div key={task.id} className="flex items-center gap-3 rounded-xl border border-border/70 bg-background p-3"><button type="button" onClick={() => void cycle(task)} className="shrink-0 text-primary" aria-label={`Change status for ${task.title}`}>{task.status === "completed" ? <Check className="size-5" /> : task.status === "in-progress" ? <Loader2 className="size-5" /> : <Circle className="size-5" />}</button><div className="min-w-0 flex-1"><p className={`truncate text-sm font-extrabold ${task.status === "completed" ? "text-muted-foreground line-through" : ""}`}>{task.title}</p><p className="mt-1 font-mono text-[10px] uppercase tracking-[0.12em] text-muted-foreground">{statusLabel[task.status]}{task.assignedUser ? ` · ${task.assignedUser}` : ""}</p></div><button type="button" onClick={() => void remove(task.id)} className="rounded-lg p-2 text-muted-foreground transition-colors hover:bg-[#fff0ee] hover:text-destructive" aria-label={`Delete ${task.title}`}><Trash2 className="size-4" /></button></div>)}</div></CardContent></Card>;
}
